# -*- coding: utf-8 -*-
"""task_python_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GgA_LCMJc-4AICjTSzS7rs02fd0ZMGoK
"""

#Upload the dataset
from google.colab import files
import pandas as pd
import numpy as np


uploaded = files.upload()
students_file=pd.read_csv("Students.csv")

#understanding the databse

print(students_file.shape)
print(students_file.head())
print(students_file.info())
print(students_file.isnull().sum())
print('Number of Duplicates:')
print(students_file.duplicated().sum())

categorical_columns = students_file.select_dtypes(include = 'object')

for col in categorical_columns:
  print(students_file[col].value_counts)

#Handle Missing Values
students_file['State'] =  students_file['State'].fillna('Not Available')
students_file.isnull().sum()

#Encode the columns if the maching learning will be applied on the file
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
students_file['Do_Professors_Allow_Use'] = le.fit_transform(students_file['Do_Professors_Allow_Use'])
students_file['Willing_to_Pay_for_Access'] = le.fit_transform(students_file['Willing_to_Pay_for_Access'])

print(students_file.head())